import { afterEach, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { CameraDetailPage } from './CameraDetailPage';
import { camerasApi } from '../api/cameras.api';
vi.mock('../hooks/useCameraSocket', () => ({ useCameraSocket: () => ({}) }));
vi.mock('../components/LiveVideoPlayer', () => ({ LiveVideoPlayer: () => <div>Video surface</div> }));
vi.mock('../components/EventTimeline', () => ({ EventTimeline: () => <div>Activity surface</div> }));
vi.mock('../components/RecordingsList', () => ({ RecordingsList: () => <div>Recordings surface</div> }));
vi.mock('../api/cameras.api', () => ({ camerasApi: { getById: vi.fn(), connect: vi.fn(), getStreamSource: vi.fn() } }));
vi.mock('../api/detection.api', () => ({ detectionApi: { getStatus: async () => ({ enabled: false, running: false }) } }));
afterEach(() => { cleanup(); vi.clearAllMocks(); });
it('keeps one detection card through repeated connect clicks and camera editing', async () => {
  const camera = { id: 'one', name: 'Entrance', pluginType: 'ONVIF', status: 'ERROR', connectionConfig: {} };
  vi.mocked(camerasApi.getById).mockResolvedValue(camera as any);
  let finish!: (result: any) => void;
  vi.mocked(camerasApi.connect).mockImplementation(() => new Promise(resolve => { finish = resolve; }));
  const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } });
  render(<QueryClientProvider client={client}><MemoryRouter initialEntries={['/cameras/one']}><Routes><Route path="/cameras/:id" element={<CameraDetailPage />} /></Routes></MemoryRouter></QueryClientProvider>);
  await screen.findByText('Entrance');
  const connect = screen.getByRole('button', { name: 'Connect camera' });
  fireEvent.click(connect); fireEvent.click(connect);
  await act(async () => { await Promise.resolve(); });
  expect(camerasApi.connect).toHaveBeenCalledTimes(1);
  expect(screen.getAllByTestId('person-detection-card')).toHaveLength(1);
  await act(async () => { finish({ id: 'one', status: 'ERROR' }); });
  fireEvent.click(screen.getByLabelText('Edit camera settings'));
  expect(screen.getByRole('dialog')).toBeDefined();
  expect(screen.getAllByTestId('person-detection-card')).toHaveLength(1);
  fireEvent.click(screen.getByLabelText('Close camera settings'));
  fireEvent.click(screen.getByRole('button', { name: 'Connect camera' }));
  await act(async () => { await Promise.resolve(); });
  expect(camerasApi.connect).toHaveBeenCalledTimes(2);
  await act(async () => { finish({ id: 'one', status: 'ERROR' }); });
  expect(screen.getAllByTestId('person-detection-card')).toHaveLength(1);
  expect(screen.queryByText('Person detection (YOLO)')).toBeNull();
  client.clear();
});
